package com.example.androidworrkshop.model

data class MatchHeader(
    var alertType: String,
    var complete: Boolean,
    var dayNight: Boolean,
    var domestic: Boolean,
    var isMatchNotCovered: Boolean,
    var livestreamEnabled: Boolean,
    var matchCompleteTimestamp: Long,
    var matchDescription: String,
    var matchFormat: String,
    var matchId: Int,
    var matchStartTimestamp: Long,
    var matchTeamInfo: List<MatchTeamInfo>,
    var matchType: String,
    var playersOfTheMatch: List<PlayersOfTheMatch>,
    var playersOfTheSeries: List<Any>,
    var result: Result,
    var revisedTarget: RevisedTarget,
    var seriesDesc: String,
    var seriesId: Int,
    var seriesName: String,
    var state: String,
    var status: String,
    var team1: Team1X,
    var team2: Team1X,
    var tossResults: TossResults,
    var year: Int
)